### ISSUE TITLE
Setup.py does not copy utils folder.

### ISSUE THREAD

**Issue by Olegandr** [tlsfuzzer/tlsfuzzer#666]
# Bug Report
I install tlsfuzzer using setup.py install
if i try to run fuzzing scripts statement 
from tlsfuzzer.utils.lists import natural_sort_keys
fails, apparently utils folder never makes it to installation folder.
## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Windows    |  |
| 10 |  |
| 3.8|  |
| 0.8.0      |  |
| tlsfuzzer revision       |  |

## Problem description

I install tlsfuzzer using setup.py install
if i try to run fuzzing scripts 
from tlsfuzzer.utils.lists import natural_sort_keys
statement fails, apparently utils folder never makes it to installation folder.

## Describe how to reproduce the problem

(if the issue is interaction with some other system/library/application,
please provide relevant version numbers or commit IDs of it too.)

Steps to reproduce the behaviour:

1. First ...
1. Then ...
1. Finally ...

## Expected behaviour

A concise description of what you expected to happen.

**Comment by tomato42** [comment]
where did you find documentation instructing you to install tlsfuzzer?

**Comment by Olegandr** [comment]
I just followed universal rules. Am I wrong? I could not found any install instructions to be frank.

**Comment by tomato42** [comment]
yes, tlsfuzzer is not installable, you run it in-place, as the examples in README suggest

**Comment by Olegandr** [comment]
I try to run test scrypts as per usage.md instructions and not able to do that, 
"fail to import from tlsfuzzer"
What is the correct way for running it then?

**Comment by tomato42** [comment]
what error do you get after running the following?:
```
git clone https://github.com/tomato42/tlsfuzzer.git
cd tlsfuzzer
pip3 install -r requirements.txt
PYTHONPATH=. python3 scripts/test-conversation.py
```

**Comment by tomato42** [comment]
aah, sorry, didn't notice you're running on Windows, you need to use `set` to set the environment variable, like so:
```
set PYTHONPATH .
python3 scripts/test-conversation.py
```
