### ISSUE TITLE
Timing based ECDSA key recovery

### ISSUE THREAD

**Issue by tomato42** [tlsfuzzer/tlsfuzzer#677]
The Minerva attack describes how to recover the ECDSA key from the server based on time it takes it to create ECDSA signatures.

https://minerva.crocs.fi.muni.cz/

by having access to private key of the server we should be able to extract the nonce used for signature and thus calculate the classes for timing behaviour (i.e. mark with class 0 signatures that use nonce with bit length == to order, 1 for ones that use nonce a bit smaller, etc.)

**Comment by GeorgePantelakis** [comment]
Tlsfuzzer now includes Minerva attack gathering, extraction and analysis.
