### ISSUE TITLE
Python 3.12 deprecated asyncore, tlslite uses it...

### ISSUE THREAD

**Issue by nrathaus** [tlsfuzzer/tlsfuzzer#899]
Tried using tlsfuzzer on Python 3.12.1 (latest version)

Moved back to Python 3.10, it seems some things got broken due to tlslite using:
```
/tlslite/integration/tlsasyncdispatchermixin.py:10: DeprecationWarning: The asyncore module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
```

It seems there is an issue open for it:
https://github.com/tlsfuzzer/tlslite-ng/issues/501

So I am writing this here to document it as well

**Comment by tomato42** [comment]
no, it doesn't use it: asyncore dependency was made optional back in alpha46: https://github.com/tlsfuzzer/tlslite-ng/commit/a9bd0a75
