### ISSUE TITLE
Hamming weight data extraction for ECDSA signatures

### ISSUE THREAD

**Issue by tomato42** [tlsfuzzer/tlsfuzzer#917]
# Feature request

## Is your feature request related to a problem? Please describe

With #909 merged, we have code now to analyse the relationship of Hamming weight with the timing of the signing, but the `extract.py` doesn't generate the appropriate files.

## Describe the solution you'd like

`extract.py` should create measurements.csv file appropriate for the Hamming weight analysis of the timing data

## Describe alternatives you've considered

There's really no alternative...

## Additional context

generating data files for both `k` and modular multiplicative inverse of `k` may be a good idea...

**Comment by GeorgePantelakis** [comment]
@tomato42 we should close this one as done, right?

**Comment by tomato42** [comment]
it extracts them by default (both the Hamming weight and Hamming weight of the multiplicative inverse)?
