### ISSUE TITLE
Can TLS-Fuzzer Simulate Handshake with Specific PSK for Encrypting Data?

### ISSUE THREAD

**Issue by hamma96** [tlsfuzzer/tlsfuzzer#962]
### Discussed in https://github.com/tlsfuzzer/tlsfuzzer/discussions/961

<div type='discussions-op-text'>

<sup>Originally posted by **hamma96** October  1, 2024</sup>

**Discussion:**

I am using **TLS-Fuzzer** to simulate a full TLS handshake with a pre-shared key (PSK) and would like to know if it's possible to configure a specific PSK value for the encrypted handshake messages.

### Scenario:

- **Client:** TLS-Fuzzer
- **Server:** A dummy web server (acting as the TLS server)
  
In my specific use case, the key for encrypting the third message in the TLS 1.2 handshake (i.e., the **Client Finished** message) should be derived from the following parameters:

1. Client random number
2. Server random number
3. Pre-Shared Key (PSK)

### Question:

How can I set a specific PSK value in **TLS-Fuzzer** to be used during the handshake process, particularly for generating the encryption key for the Client Finished message?

I have not been able to find documentation or examples on how to configure the PSK in the TLS-Fuzzer. Is there an existing way to:

1. **Set a custom PSK** for the handshake?
2. Ensure the PSK is used in conjunction with the Client and Server random values to generate the key for encryption?

Any guidance or examples would be greatly appreciated!
</div>

**Comment by tomato42** [comment]
Lack of support for PSK is tracked in #55, discussion in https://github.com/tlsfuzzer/tlsfuzzer/discussions/961
